jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install -e ".[dev]"'
    - name: Run linters
      run: echo "No linters configured"
    - name: Run tests
      run: python -m unittest
    - name: GitMove Branch Validation
      run: gitmove check-conflicts
    strategy:
      matrix:
        python-version:
        - '3.9'
        - '3.10'
name: GitMove Workflow
'on':
  pull_request:
    branches:
    - master
    - develop
  push:
    branches:
    - master
    - develop
